// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:book_search/domain/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsDtoAdapter());
    registerAdapter(AuthorDtoAdapter());
    registerAdapter(SubjectDtoAdapter());
    registerAdapter(WorkDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsDtoAdapter());
    registerAdapter(AuthorDtoAdapter());
    registerAdapter(SubjectDtoAdapter());
    registerAdapter(WorkDtoAdapter());
  }
}
